<?php
return [
  'gilipollas',
  'culo',
  'bastardo',
  'perra',
  'cojones',
  'coño',
  'cabeza de pene',
  'maricón',
  'jodido',
  'hijodeputa',
  'negro',
  'punto G',
  'imbécil',
  'cabeza de mierda',
  'zorra',
  'vagina',
  'follar',
  'tirarse a alguien',
  'cara de coño',
  'pajero',
  'bimbo',
  'cara de polla',
  'consolador',
  'idiota',
  'retrasado',
  'idiota del culo',
  'eyaculación',
  'jodido',
  'pajearse',
  'clítoris',
  'chino',
  'drogadicto',
  'chupapollas',
  'pendejo',
  'lesbiana',
  'marica',
  'puño en el culo',
  'cara de mierda',
  'prostituta',
  'sexo extremo',
  'mancha de semen',
  'judío',
  'gordo de mierda',
  'lesbiana',
  'tonto del culo',
  'sexista',
  'bolsa de mierda',
  'frotamiento lésbico',
  'zorra',
  'latino',
  'cállate la boca',
  'travesti',
  'burdel',
  'hijoputa',
  'culo de mierda',
  'follar por el culo',
  'imbécil',
  'asqueroso',
  'payaso del culo',
  'follador de culos',
  'lamedor de culos',
  'mordedor de culos',
  'mexicano',
  'capullo',
  'mamada',
  'erección',
  'aumento de pecho',
  'sodomizar',
  'tonterías',
  'comepelos',
  'polla pequeña',
  'cara de clítoris',
  'desastre total',
  'negro',
  'culo apretado',
  'puta del semen',
  'cara de coño',
  'labios de coño',
  'bolsa de pene',
  'agujero de pene',
  'bofetada de pene',
  'posición perrito',
  'imbécil',
  'chupador de semen',
  'vagina de plástico',
  'azotar',
  'prepucio',
  'pervertido',
  'orgía',
  'rajadura',
  'perineo',
  'erección dura',
  'cara de semen',
  'cabeza hueca',
  'coño peludo',
  'chupador de coño',
  'cabeza de polla',
  'cara de pene',
  'chocha',
  'ano',
  'pedo vaginal',
  'cabeza de trapo',
  'sexo anal',
  'cara de escroto',
  'pene grande',
  'borracho de mierda',
  'agujero de mierda',
  'mierda',
  'chorro de semen',
  'tetas grandes',
  'perineo',
  'follarse tetas',
  'masturbador',
  'imbécil total',
  'coño',
  'mancha de semen',
  'ano con cuentas',
  'bastardo',
  'dientes de castor',
  'nalgas',
  'puño en la polla',
  'bloqueador de pollas',
  'eyaculación interna',
  'contenedor de semen',
  'cubeta de semen',
  'nariz de pene',
  'estupidez',
  'fist me',
  'mierda pegajosa',
  'limpiador de semen',
  'trabajo de lubricante',
  'sexo oral',
  'cabeza de ano',
  'juguete sexual',
  'esmegma',
  'burbuja de semen',
  'chupa pollas',
  'testículos',
  'trío',
  'vagabunda',
  'pajero',
  'culo mojado',
  'bolsa de puta',
  'no importas',
  'garra de cangrejo',
  'bola de culo',
  'cuello de ganso',
  'fiesta de fisting',
  'tostada de polla',
  'culo engreído',
  'inmersión profunda',
  'trapos de semen',
  'duende de mierda',
  'coño fantástico',
  'torpedo de polla',
  'duende de zorras',
  'prostituta adicta',
  'reina bimbo',
  'testículos',
  'bastardo',
  'chúpamela',
  'rey de las putas',
  'sudoroso',
  'agujero de culo',
  'lábios de orina',
  'cara de mierda',
  'pirata del culo',
  'jinete de coño',
  'payaso follador',
  'grieta anal',
  'adicto al sexo',
  'puñetazo',
  'culo de mierda',
  'puta del semen',
  'chupador de clítoris',
  'asesino de culos',
  'cubeta de semen',
  'agujero de soplo',
  'agujero apestoso',
  'nariz de pene',
  'lamedor de pene',
  'cara de mierda',
  'garganta de pene',
  'dolor de culo',
  'rey del fisting',
  'destroza culos',
  'lamedor de orina',
  'labios de pene',
  'adicto al semen',
  'susurrador de pollas',
  'chupador de culos',
  'juego de palabras',
  'bastardo',
  'recto destrozado',
  'pervertido',
  'payaso de polla',
  'sexo',
  'sexy',
  'cabeza de mierda',
  'agarrador de coños',
  'puta rara',
  'cesta de coños',
  'lamedor de culos',
  'culo de retrete',
  'apilador de culos',
  'tragador de mierda',
  'cracker de mierda',
  'golpeador de semen',
  'escoria de basura',
  'bolsillo caliente',
  'reventador de pollas',
  'imbécil',
  'cara de culo',
  'agujero de mierda',
  'agujero de pene'
];
