<?php
return [
  'connard',
  'cul',
  'bâtard',
  'salope',
  'couilles',
  'connasse',
  'abruti',
  'pédé',
  'putain',
  'enculé',
  'nègre',
  'point G',
  'bite',
  'tête de merde',
  'pute',
  'chatte',
  'merde',
  'baiser',
  'face de con',
  'branleur',
  'bimbo',
  'gueule de bite',
  'godemichet',
  'crétin',
  'retardé',
  'abruti de service',
  'éjaculation',
  'merdique',
  'branlette',
  'clitoris',
  'chinetoque',
  'toxicomane',
  'suceur de bite',
  'connard de merde',
  'gouine',
  'tapette',
  'doigté',
  'face de merde',
  'prostituée',
  'exhibitionniste',
  'trace de sperme',
  'youpin',
  'gros cul',
  'lesbienne',
  'abruti fini',
  'sexiste',
  'sac à merde',
  'ciseaux',
  'trainée',
  'spic',
  'ferme ta gueule',
  'travelo',
  'bordel',
  'putain de merde',
  'trou du cul',
  'enculade',
  'trou de balle',
  'gros moche',
  'bouffon',
  'enculeur',
  'lécheur de cul',
  'mange-merde',
  'métèque',
  'gland',
  'fellation',
  'érection',
  'augmentation mammaire',
  'enculé',
  'conneries',
  'bouffeur de tapis',
  'chibre',
  'face de clito',
  'bordel de merde',
  'négro',
  'cul en feu',
  'salope à sperme',
  'gueule de conne',
  'lèvres de chatte',
  'sac à bite',
  'trou de bite',
  'gifle de bite',
  'levrette',
  'trou du cul',
  'suceur',
  'sextoy',
  'prépuce',
  'branleur',
  'partouze',
  'fente',
  'périnée',
  'érection',
  'gueule à sperme',
  'gros beauf',
  'foufoune',
  'bouffeur de chatte',
  'tête de gland',
  'face de bite',
  'minou',
  'trou du cul',
  'pet vaginal',
  'bougnoule',
  'anulingus',
  'face de couilles',
  'grosse bite',
  'bourré comme un cochon',
  'trou de merde',
  'merdier',
  'éjaculat',
  'nichons',
  'sillon inter-fessier',
  'baise nichons',
  'branleur',
  'crêpe de chatte',
  'foufoune',
  'tache de sperme',
  'cul',
  'pervers sexuel',
  'cul sale',
  'bordel ambulant',
  'pute à fric',
  'sale pute',
  'reine des salopes',
  'couilles',
  'baiser profond',
  'chiffon à sperme',
  'gobelin à merde',
  'bâtard',
  'paye-moi une pipe',
  'roi des salopes',
  'strapontin de jock',
  'trou du cul',
  'lèvres de merde',
  'face de merde',
  'pirate du cul',
  'cavalier de chatte',
  'clown baiseur',
  'fissure anale',
  'obsédé sexuel',
  'poing en l’air',
  'cul merdeux',
  'pute à sperme',
  'lécheuse de chatte',
  'cul sur cul',
  'seau à sperme',
  'trou de bite',
  'trou sale',
  'nez de bite',
  'lèche-bite',
  'gueule de merde',
  'gorge profonde',
  'cul douloureux',
  'roi du fist',
  'exploseur de cul',
  'lécheur de pisse',
  'lèvres de bite',
  'obsédé du sperme',
  'chuchoteur de bite',
  'suceur de cul',
  'bâtard',
  'ruine rectale',
  'freak',
  'clown à bite',
  'sexe',
  'sexy',
  'Pénis',
  'tête de merde',
  'attrape-minou',
  'pute bizarre',
  'panier à chatte',
  'lécheur de cul',
  'cul de toilettes',
  'empileur de culs',
  'mangeur de merde',
  'craqueur de merde',
  'frappeur de sperme',
  'déchet',
  'chaussette chaude',
  'casseur de chibre',
  'connard',
  'face de bite',
  'trou de merde',
  'trou de bite'
];
